# 整个流程的名字
name: Release

# 触发时机，在 main 分支 push 操作触发
on:
  push:
    branches:
      - chore-ci
  # pull_request:
  #   types:
  #     - labeled
  #     - unlabeled
  #     - synchronize
  #     - opened
  #     - edited
  #     - ready_for_review
  #     - reopened
  #     - unlocked
  # pull_request_review:
  #   types:
  #     - submitted
  # status: {}

permissions:
  contents: write
  pull-requests: write


# 任务，定义个changelog 的任务
jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16


      # - name: checkout
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.inputs.branch }}

      - name: init
        run: npm i install yarn lerna@^4 typescript -g

      - name: install
        run: yarn initialize

      - name: build
        run: yarn build

      - name: prerelease
        run: lerna version prerelease
        env:
          GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepublish
        run: lerna publish from-package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - uses: google-github-actions/release-please-action@v4
      #   with:
      #     # this assumes that you have created a personal access token
      #     # (PAT) and configured it as a GitHub action secret named
      #     # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # this is a built-in strategy in release-please, see "Action Inputs"
      #     # for more options
      #     release-type: simple

      #     target-branch: 'master'